InAndOut/UploadFile/Pages/AttendanceCreate.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using UploadFile;
using UploadFile.Data;

namespace UploadFile.Pages
{
    public class AttendanceCreateModel : PageModel
    {
        private readonly UploadFile.UploadfileContext _context;

        public AttendanceCreateModel(UploadFile.UploadfileContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Attendances Attendances { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attendances.Add(Attendances);
            await _context.SaveChangesAsync();

            return RedirectToPage("./AttendanceIndex");
        }
    }
}

InAndOut/UploadFile/Pages/AttendanceIndex.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using UploadFile.Data;

namespace UploadFile.Pages
{
    public class AttendanceIndexModel : PageModel
    {
        private readonly ILogger<AttendanceIndexModel> _logger;

        private readonly UploadfileContext _context;

        public AttendanceIndexModel(ILogger<AttendanceIndexModel> logger, UploadfileContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IList<Attendances> Attendances { get; set; }

        public void OnGet(string searchby, string search)
        {
            if (searchby == "Reference")
            {
                IEnumerable<Attendances> objList = _context.Attendances;
                Attendances = _context.Attendances.Where(x => x.Reference == search || search == null).ToList();

            }

            else
            {
                IEnumerable<Attendances> objList = _context.Attendances;
                Attendances = _context.Attendances.Where(x => x.Name == search || search == null).ToList();

            }

        }

        public async Task<IActionResult> OnPostDownloadAsync(int? id)
        {
            var myInv = await _context.Attendances.FirstOrDefaultAsync(m => m.Id == id);
            if (myInv == null)
            {
                return NotFound();
            }

            if (myInv.Attachment == null)
            {
                return Page();
            }
            else
            {
                byte[] byteArr = myInv.Attachment;
                string mimeType = "application/pdf";
                return new FileContentResult(byteArr, mimeType)
                {
                    FileDownloadName = $"Attendances {myInv.Number}.pdf"
                };
            }

        }

        public async Task<IActionResult> OnPostDeleteAsync(int? id)
        {
            var myInv = await _context.Attendances.FirstOrDefaultAsync(m => m.Id == id);
            if (myInv == null)
            {
                return NotFound();
            }

            if (myInv.Attachment == null)
            {
                return Page();
            }
            else
            {
                myInv.Attachment = null;
                _context.Update(myInv);
                await _context.SaveChangesAsync();
            }

            Attendances = await _context.Attendances.ToListAsync();
            return Page();
        }
    }
}

InAndOut/UploadFile/Pages/AttendanceUpload.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UploadFile.Pages
{
    public class AttendanceUploadModel : PageModel
    {

        private readonly UploadfileContext _context;

        public AttendanceUploadModel(UploadfileContext context)
        {

            _context = context;
        }
        public int? myID { get; set; }

        [BindProperty]
        public IFormFile file { get; set; }

        [BindProperty]
        public int? ID { get; set; }
        public void OnGet(int? id)
        {
            myID = id;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (file != null)
            {
                if (file.Length > 0 && file.Length < 300000)
                {
                    var myInv = _context.Attendances.FirstOrDefault(x => x.Id == ID);

                    using (var target = new MemoryStream())
                    {
                        file.CopyTo(target);
                        myInv.Attachment = target.ToArray();
                    }

                    _context.Attendances.Update(myInv);
                    await _context.SaveChangesAsync();
                }

            }

            return RedirectToPage("./AttendanceIndex");
        }

    }
}

InAndOut/UploadFile/Pages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using UploadFile;
using UploadFile.Data;

namespace UploadFile.Pages
{
    public class CreateModel : PageModel
    {
        private readonly UploadFile.UploadfileContext _context;

        public CreateModel(UploadFile.UploadfileContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Students Students { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Students.Add(Students);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

InAndOut/UploadFile/Pages/EmployeeCreate.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using UploadFile;
using UploadFile.Data;

namespace UploadFile.Pages
{
    public class EmployeeCreateModel : PageModel
    {
        private readonly UploadFile.UploadfileContext _context;

        public EmployeeCreateModel(UploadFile.UploadfileContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Employees Employees { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Employees.Add(Employees);
            await _context.SaveChangesAsync();

            return RedirectToPage("./EmployeeIndex");
        }
    }
}

InAndOut/UploadFile/Pages/EmployeeIndex.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using UploadFile.Data;

namespace UploadFile.Pages
{
    public class EmployeeIndexModel : PageModel
    {
        private readonly ILogger<EmployeeIndexModel> _logger;

        private readonly UploadfileContext _context;

        public EmployeeIndexModel(ILogger<EmployeeIndexModel> logger, UploadfileContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IList<Employees> Employees { get; set; }

        public void OnGet(string searchby, string search)
        {
            if (searchby == "Reference")
            {
                IEnumerable<Employees> objList = _context.Employees;
                Employees = _context.Employees.Where(x => x.Reference == search || search == null).ToList();

            }

            else
            {
                IEnumerable<Employees> objList = _context.Employees;
                Employees = _context.Employees.Where(x => x.Name == search || search == null).ToList();

            }

        }

        public async Task<IActionResult> OnPostDownloadAsync(int? id)
        {
            var myInv = await _context.Employees.FirstOrDefaultAsync(m => m.Id == id);
            if (myInv == null)
            {
                return NotFound();
            }

            if (myInv.Attachment == null)
            {
                return Page();
            }
            else
            {
                byte[] byteArr = myInv.Attachment;
                string mimeType = "application/pdf";
                return new FileContentResult(byteArr, mimeType)
                {
                    FileDownloadName = $"Employees {myInv.Number}.pdf"
                };
            }

        }

        public async Task<IActionResult> OnPostDeleteAsync(int? id)
        {
            var myInv = await _context.Employees.FirstOrDefaultAsync(m => m.Id == id);
            if (myInv == null)
            {
                return NotFound();
            }

            if (myInv.Attachment == null)
            {
                return Page();
            }
            else
            {
                myInv.Attachment = null;
                _context.Update(myInv);
                await _context.SaveChangesAsync();
            }

            Employees = await _context.Employees.ToListAsync();
            return Page();
        }
    }
}

InAndOut/UploadFile/Pages/EmployeeUpload.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UploadFile.Pages
{
    public class EmployeeUploadModel : PageModel
    {

        private readonly UploadfileContext _context;

        public EmployeeUploadModel(UploadfileContext context)
        {

            _context = context;
        }
        public int? myID { get; set; }

        [BindProperty]
        public IFormFile file { get; set; }

        [BindProperty]
        public int? ID { get; set; }
        public void OnGet(int? id)
        {
            myID = id;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (file != null)
            {
                if (file.Length > 0 && file.Length < 300000)
                {
                    var myInv = _context.Employees.FirstOrDefault(x => x.Id == ID);

                    using (var target = new MemoryStream())
                    {
                        file.CopyTo(target);
                        myInv.Attachment = target.ToArray();
                    }

                    _context.Employees.Update(myInv);
                    await _context.SaveChangesAsync();
                }

            }

            return RedirectToPage("./EmployeeIndex");
        }

    }
}

InAndOut/UploadFile/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace UploadFile.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

InAndOut/UploadFile/Pages/ExamCreate.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using UploadFile;
using UploadFile.Data;

namespace UploadFile.Pages
{
    public class ExamCreateModel : PageModel
    {
        private readonly UploadFile.UploadfileContext _context;

        public ExamCreateModel(UploadFile.UploadfileContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Exams Exams { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Exams.Add(Exams);
            await _context.SaveChangesAsync();

            return RedirectToPage("./ExamIndex");
        }
    }
}

InAndOut/UploadFile/Pages/ExamIndex.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using UploadFile.Data;

namespace UploadFile.Pages
{
    public class ExamIndexModel : PageModel
    {
        private readonly ILogger<ExamIndexModel> _logger;

        private readonly UploadfileContext _context;

        public ExamIndexModel(ILogger<ExamIndexModel> logger, UploadfileContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IList<Exams> Exams { get; set; }

        public void OnGet(string searchby, string search)
        {
            if (searchby == "Reference")
            {
                IEnumerable<Exams> objList = _context.Exams;
                Exams = _context.Exams.Where(x => x.Reference == search || search == null).ToList();

            }

            else
            {
                IEnumerable<Exams> objList = _context.Exams;
                Exams = _context.Exams.Where(x => x.Name == search || search == null).ToList();

            }

        }

        public async Task<IActionResult> OnPostDownloadAsync(int? id)
        {
            var myInv = await _context.Exams.FirstOrDefaultAsync(m => m.Id == id);
            if (myInv == null)
            {
                return NotFound();
            }

            if (myInv.Attachment == null)
            {
                return Page();
            }
            else
            {
                byte[] byteArr = myInv.Attachment;
                string mimeType = "application/pdf";
                return new FileContentResult(byteArr, mimeType)
                {
                    FileDownloadName = $"Exams {myInv.Number}.pdf"
                };
            }

        }

        public async Task<IActionResult> OnPostDeleteAsync(int? id)
        {
            var myInv = await _context.Exams.FirstOrDefaultAsync(m => m.Id == id);
            if (myInv == null)
            {
                return NotFound();
            }

            if (myInv.Attachment == null)
            {
                return Page();
            }
            else
            {
                myInv.Attachment = null;
                _context.Update(myInv);
                await _context.SaveChangesAsync();
            }

            Exams = await _context.Exams.ToListAsync();
            return Page();
        }
    }
}

InAndOut/UploadFile/Pages/FinanceCreate.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using UploadFile;
using UploadFile.Data;

namespace UploadFile.Pages
{
    public class FinanceCreateModel : PageModel
    {
        private readonly UploadFile.UploadfileContext _context;

        public FinanceCreateModel(UploadFile.UploadfileContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Finances Finances { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Finances.Add(Finances);
            await _context.SaveChangesAsync();

            return RedirectToPage("./FinanceIndex");
        }
    }
}

InAndOut/UploadFile/Pages/AttendanceIndex.cshtml
@page
@model AttendanceIndexModel
@{
    ViewData["Title"] = "Attendance";
}


<h1>Attendance Document Management</h1>

<p>
    <a asp-page="AttendanceCreate">Document Details</a>
</p>

<p>
    @using (Html.BeginForm("AttendanceIndex", "AttendanceIndex", FormMethod.Get))
    {
        <b>Search</b>@Html.RadioButton("Searchby", "Reference", true)<b>Reference</b>
        @Html.RadioButton("Searchby", "Name")<b>Name</b>
        @Html.TextBox("Search")<input type="submit" value="Search" />

    }
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Attendances[0].Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Attendances[0].Reference)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Attendances[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Attendances[0].Date)
            </th>
            <th>
                Upload
            </th>
            <th>Download</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Attendances)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reference)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                <a asp-page="AttendanceUpload" asp-route-id="@item.Id">Upload Document</a>
            </td>
            <td>
                @if (item.Attachment != null)
                {
                    <form asp-page-handler="Download" method="post" asp-route-id="@item.Id">
                        <input type="submit" 
                               class="btn btn-outline-dark"
                               onclick="return confirm('Are you sure you want to Download the record')"
                               value="Download">
                    </form>
                }
            </td>
            <td>
                @if (item.Attachment != null)
                {
                    <form asp-page-handler="Delete" method="post" asp-route-id="@item.Id">
                        <input type="submit" 
                               class="btn btn-outline-danger"
                               onclick="return confirm('Are you sure you want to Delete the record')"
                               value="Delete">
                    </form>
                }
            </td>
        </tr>
        }
    </tbody>
</table>

InAndOut/UploadFile/Pages/AttendanceUpload.cshtml
@page
@model UploadFile.Pages.AttendanceUploadModel
@{
}

<h1>Upload Attendance Document</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <div class="col-md-10">
                    <p>Upload file</p>
                    <input type="hidden" asp-for="@Model.ID" value="@Model.myID" />
                    <input asp-for="file" class="form-control" accept=".pdf" type="file" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <input class="btn btn-outline-success" type="submit" value="Upload" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="AttendanceIndex">Back to List</a>
</div>

InAndOut/UploadFile/Pages/EmployeeUpload.cshtml
@page
@model UploadFile.Pages.EmployeeUploadModel
@{
}

<h1>Upload Employee Document</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <div class="col-md-10">
                    <p>Upload file</p>
                    <input type="hidden" asp-for="@Model.ID" value="@Model.myID" />
                    <input asp-for="file" class="form-control" accept=".pdf" type="file" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <input class="btn btn-outline-success" type="submit" value="Upload" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="EmployeeIndex">Back to List</a>
</div>

InAndOut/UploadFile/Pages/ExamIndex.cshtml
@page
@model ExamIndexModel
@{
    ViewData["Title"] = "Exam";
}


<h1>Exam Result Document Management</h1>

<p>
    <a asp-page="ExamCreate">Document Details</a>
</p>

<p>
    @using (Html.BeginForm("ExamIndex", "ExamIndex", FormMethod.Get))
    {
        <b>Search</b>@Html.RadioButton("Searchby", "Reference", true)<b>Reference</b>
        @Html.RadioButton("Searchby", "Name")<b>Name</b>
        @Html.TextBox("Search")<input type="submit" value="Search" />

    }
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Exams[0].Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Exams[0].Reference)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Exams[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Exams[0].Date)
            </th>
            <th>
            <th>
                Upload
            </th>
            <th>Download</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Exams)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reference)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
            <td>
                <a asp-page="ExamUpload" asp-route-id="@item.Id">Upload Document</a>
            </td>
            <td>
                @if (item.Attachment != null)
                {
                    <form asp-page-handler="Download" method="post" asp-route-id="@item.Id">
                        <input type="submit" 
                               class="btn btn-outline-dark"
                               onclick="return confirm('Are you sure you want to Download the record')"
                               value="Download">
                    </form>
                }
            </td>
            <td>
                @if (item.Attachment != null)
                {
                    <form asp-page-handler="Delete" method="post" asp-route-id="@item.Id">
                        <input type="submit" 
                               class="btn btn-outline-danger"
                               onclick="return confirm('Are you sure you want to Delete the record')"
                               value="Delete">
                    </form>
                }
            </td>
        </tr>
        }
    </tbody>
</table>

InAndOut/UploadFile/Pages/FinanceIndex.cshtml
@page
@model FinanceIndexModel
@{
    ViewData["Title"] = "Finance";
}


<h1>Finance Document Management</h1>

<p>
    <a asp-page="FinanceCreate">Document Details</a>
</p>

<p>
    @using (Html.BeginForm("FinanceIndex", "FinanceIndex", FormMethod.Get))
    {
        <b>Search</b>@Html.RadioButton("Searchby", "Reference", true)<b>Reference</b>
        @Html.RadioButton("Searchby", "Name")<b>Name</b>
        @Html.TextBox("Search")<input type="submit" value="Search" />

    }
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Finances[0].Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Finances[0].Reference)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Finances[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Finances[0].Date)
            </th>
            <th>
                Upload
            </th>
            <th>Download</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Finances)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Reference)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    <a asp-page="FinanceUpload" asp-route-id="@item.Id">Upload Document</a>
                </td>
                <td>
                    @if (item.Attachment != null)
                    {
                        <form asp-page-handler="Download" method="post" asp-route-id="@item.Id">
                            <input type="submit" 
                                   class="btn btn-outline-dark"
                                   onclick="return confirm('Are you sure you want to Download the record')"
                                   value="Download">
                        </form>
                    }
                </td>
                <td>
                    @if (item.Attachment != null)
                    {
                        <form asp-page-handler="Delete" method="post" asp-route-id="@item.Id">
                            <input type="submit" 
                                   class="btn btn-outline-danger"
                                   onclick="return confirm('Are you sure you want to Delete the record')"
                                   value="Delete">
                        </form>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

InAndOut/UploadFile/Pages/FinanceUpload.cshtml
@page
@model UploadFile.Pages.FinanceUploadModel
@{
}

<h1>Upload Finance Document</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <div class="col-md-10">
                    <p>Upload file</p>
                    <input type="hidden" asp-for="@Model.ID" value="@Model.myID" />
                    <input asp-for="file" class="form-control" accept=".pdf" type="file" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <input class="btn btn-outline-success" type="submit" value="Upload" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="FinanceIndex">Back to List</a>
</div>

InAndOut/UploadFile/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Student";
}


<h1>Student Document Management</h1>

<p>
    <a asp-page="Create">Document Details</a>
</p>


<p>
    @using (Html.BeginForm("Index", "Index", FormMethod.Get))
    {
        <b>Search</b>@Html.RadioButton("Searchby", "Reference", true)<b>Reference</b>
        @Html.RadioButton("Searchby", "Name")<b>Name</b>
        @Html.TextBox("Search")<input type="submit" value="Search" />

    }
</p>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Students[0].Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Students[0].Reference)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Students[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Students[0].Date)
            </th>
            <th>
                Upload
            </th>
            <th>Download</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Students)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Reference)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    <a asp-page="Upload" asp-route-id="@item.Id">Upload Document</a>
                </td>
                <td>
                    @if (item.Attachment != null)
                    {
                        <form asp-page-handler="Download" method="post" asp-route-id="@item.Id">
                            <input type="submit" 
                                   class="btn btn-outline-dark"
                                   onclick="return confirm('Are you sure you want to Download the record')"
                                   value="Download">
                        </form>
                    }
                </td>
                <td>
                    @if (item.Attachment != null)
                    {
                        <form asp-page-handler="Delete" method="post" asp-route-id="@item.Id">
                            <input type="submit" 
                                   class="btn btn-outline-danger"
                                   onclick="return confirm('Are you sure you want to Delete the record')"
                                   value="Delete">
                        </form>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>