InAndOut/InAndOut/Models/Attendance.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Models
{
    public class Attendance
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string AttendanceDate { get; set; }
        public string ArrivalTime { get; set; }
        public string DepartureTime { get; set; }
    }
}

InAndOut/InAndOut/Controllers/AttendanceController.cs
using InAndOut.Data;
using InAndOut.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Controllers
{
    [Authorize]
    public class AttendanceController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AttendanceController(ApplicationDbContext db)
        {
            _db = db;
        }


        [AcceptVerbs("GET", "POST")]
        public ActionResult Index(string searchTxt, string SortOrder, string SortBy, int PageNumber = 1)
        {

            ViewBag.SortOrder = SortOrder;
            ViewBag.SortBy = SortBy;

            var model = _db.Attendances.ToList();


            if (searchTxt != null)
            {
                model = _db.Attendances.Where(x => x.Name.Contains(searchTxt)).ToList();
                //model = _db.Attendances.Where(x => x.Name.Contains(searchTxt) || x.ArrivalTime.Contains(searchTxt) || x.DepartureTime.Contains(searchTxt)).ToList();
                ApplySorting(SortOrder, SortBy, model);
                model = ApplyPagination(model, PageNumber);

            }

            else
            {

                ApplySorting(SortOrder, SortBy, model);
                model = ApplyPagination(model, PageNumber);

            }


            return View(model);


        }

        public void ApplySorting(string SortOrder, string SortBy, List<Attendance> model)
        {

            switch (SortBy)
            {
                case "Name":
                    {
                        switch (SortOrder)
                        {
                            case "Asc":
                                {
                                    model = model.OrderBy(x => x.Name).ToList();
                                    break;
                                }

                            case "Desc":
                                {
                                    model = model.OrderByDescending(x => x.Name).ToList();
                                    break;
                                }

                            default:
                                {
                                    model = model.OrderBy(x => x.Name).ToList();
                                    break;
                                }



                        }
                        break;
                    }
                case "AttendanceDate":
                    {
                        switch (SortOrder)
                        {
                            case "Asc":
                                {
                                    model = model.OrderBy(x => x.AttendanceDate).ToList();
                                    break;
                                }

                            case "Desc":
                                {
                                    model = model.OrderByDescending(x => x.AttendanceDate).ToList();
                                    break;
                                }

                            default:
                                {
                                    model = model.OrderBy(x => x.AttendanceDate).ToList();
                                    break;
                                }



                        }
                        break;
                    }

                default:
                    {
                        model = model.OrderBy(x => x.Name).ToList();
                        break;
                    }


            }

        }

        public List<Attendance> ApplyPagination(List<Attendance> model, int PageNumber)
        {

            ViewBag.TotalPages = Math.Ceiling(model.Count() / 8.0);
            ViewBag.PageNumber = PageNumber;



            model = model.Skip((PageNumber - 1) * 8).Take(8).ToList();

            return model;


        }

        // GET-Create
        public IActionResult Create()
        {
            return View();
        }

        // POST-Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Attendance obj)
        {
            if (ModelState.IsValid)
            {
                _db.Attendances.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET Delete
        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Attendances.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        // POST Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Attendances.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Attendances.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

        // GET Update
        public IActionResult Update(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Attendances.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        // POST-Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Attendance obj)
        {
            if (ModelState.IsValid)
            {
                _db.Attendances.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

    }
}

InAndOut/InAndOut/Views/Attendance/Create.cshtml
@model InAndOut.Models.Attendance

<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        @*<div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Attendance</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-3">
                        <label asp-for="AttendanceDate"></label>
                    </div>
                    <div class="col-3">
                        <label asp-for="ArrivalTime"></label>
                    </div>
                    <div class="col-3">
                        <label asp-for="DepartureTime"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-3">
                        <input asp-for="AttendanceDate" class="form-control" />
                        <span asp-validation-for="AttendanceDate" class="text-danger"></span>
                    </div>
                    <div class="col-3">
                        <input asp-for="ArrivalTime" class="form-control" />
                        <span asp-validation-for="ArrivalTime" class="text-danger"></span>
                    </div>
                    <div class="col-3">
                        <input asp-for="DepartureTime" class="form-control" />
                        <span asp-validation-for="DepartureTime" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" 
                                   class="btn btn-outline-info w-75"
                                   onclick="return confirm('Are you sure you want to Save the record')"
                                   value="create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-outline-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

InAndOut/InAndOut/Views/Attendance/Delete.cshtml
@model InAndOut.Models.Attendance

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Delete Attendance</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-3">
                        <label asp-for="AttendanceDate"></label>
                    </div>
                    <div class="col-3">
                        <label asp-for="ArrivalTime"></label>
                    </div>
                    <div class="col-3">
                        <label asp-for="DepartureTime"></label>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>
                    <div class="col-3">
                        <input asp-for="AttendanceDate" disabled class="form-control" />
                    </div>
                    <div class="col-3">
                        <input asp-for="ArrivalTime" disabled class="form-control" />
                    </div>
                    <div class="col-3">
                        <input asp-for="DepartureTime" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" 
                                   class="btn btn-outline-danger w-75"
                                   onclick="return confirm('Are you sure you want to Delete the record')"
                                   value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-outline-success w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

InAndOut/InAndOut/Views/Attendance/Index.cshtml
@model IEnumerable<InAndOut.Models.Attendance>


<div class="row pt-4">
    <div class="col-6">
        <h2 class="text-primary">Attendance List</h2>
    </div>
    <div class="col-6 text-right">
        <a asp-controller="Attendance" asp-action="Create" class="btn btn-outline-primary">Create new Attendance</a>
    </div>
</div>
<br />


@if (Model.Count() > 0)
{

    <div class="container-fluid">
        <div class="row">

            @using (Html.BeginForm("Index", "Attendance", FormMethod.Post))
            {
                <div class="form-horizontal">

                    <div class="form-group">

                        <label class="col-md-2 control-label">Search</label>

                        <div class="d-flex">

                            <input type="text" name="searchTxt" class="form-control" placeholder="Search your text here" style="max-width: 100%" />

                            <div class="ml-2">
                                <button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-search"></span>Search</button>
                            </div>
                        </div>

                    </div>


                </div>

            }

        </div>

        <div class="row">
            <div class="col-md-12">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th>
                                Id
                            </th>
                            <th style="text-align:center">
                                Name
                                @*@Html.ActionLink("Name", "Index", new { SortOrder = ViewBag.SortOrder == null ? "Asc" : (ViewBag.SortOrder == "Asc" ? "Desc" : "Asc"), SortBy = "Name", PageNumber = ViewBag.PageNumber == 0 ? 1 : ViewBag.PageNumber })*@
                            </th>
                            <th style="text-align:center">
                                Attendance Date
                                @*@Html.ActionLink("Gender", "Index", new { SortOrder = ViewBag.SortOrder == null ? "Asc" : (ViewBag.SortOrder == "Asc" ? "Desc" : "Asc"), SortBy = "Gender", PageNumber = ViewBag.PageNumber == 0 ? 1 : ViewBag.PageNumber })*@
                            </th>
                            <th style="text-align:center">
                                Arrival Time
                                @*@Html.ActionLink("Section", "Index", new { SortOrder = ViewBag.SortOrder == null ? "Asc" : (ViewBag.SortOrder == "Asc" ? "Desc" : "Asc"), SortBy = "Section", PageNumber = ViewBag.PageNumber == 0 ? 1 : ViewBag.PageNumber })*@
                            </th>
                            <th style="text-align:center">
                                Departure Time
                                @*@Html.ActionLink("BirthDate", "Index", new { SortOrder = ViewBag.SortOrder == null ? "Asc" : (ViewBag.SortOrder == "Asc" ? "Desc" : "Asc"), SortBy = "BirthDate", PageNumber = ViewBag.PageNumber == 0 ? 1 : ViewBag.PageNumber })*@
                            </th>
                            <th style="text-align:center">
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var attendance in Model)
                        {
                            <tr>
                                <td width="5%">@attendance.Id</td>
                                <td style="text-align:center" width="20%">@attendance.Name</td>
                                <td style="text-align:center" width="20%">@attendance.AttendanceDate</td>
                                <td style="text-align:center" width="20%">@attendance.ArrivalTime</td>
                                <td style="text-align:center" width="20%">@attendance.DepartureTime</td>
                                <td style="text-align:center" width="20%">
                                    <div class="w-100 btn-group" role="group">
                                        <a asp-controller="Attendance" asp-action="Update" asp-route-Id="@attendance.Id" class="btn btn-outline-primary mx-1">Update</a>
                                        <a asp-controller="Attendance" asp-action="Delete" asp-route-Id="@attendance.Id" class="btn btn-outline-danger mx-1">Delete</a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>


                @{

                    double totalPages = ViewBag.TotalPages;

                    <ul class="pagination">
                        <div class="mr-2">
                            @if (ViewBag.PageNumber == 1)
                            {
                            <li>
                                @Html.ActionLink("Previous", "Index", new { SortOrder = ViewBag.SortOrder == null ? "Asc" : ViewBag.SortOrder, SortBy = ViewBag.SortBy == null ? "Name" : ViewBag.SortBy, PageNumber = ViewBag.PageNumber })
                            </li>

                        }
                        else
                        {

                            <li>
                                @Html.ActionLink("Previous", "Index", new { SortOrder = ViewBag.SortOrder == null ? "Asc" : ViewBag.SortOrder, SortBy = ViewBag.SortBy == null ? "Name" : ViewBag.SortBy, PageNumber = ViewBag.PageNumber - 1 })
                            </li>

                        }
                    </div>



                    @for (int i = 1; i <= totalPages; i++)
                    {

                        if (i == ViewBag.PageNumber)
                        {


                            <li class="ml-3">
                                @Html.ActionLink(i.ToString(), "Index", new { SortOrder = ViewBag.SortOrder == null ? "Asc" : ViewBag.SortOrder, SortBy = ViewBag.SortBy == null ? "Name" : ViewBag.SortBy, PageNumber = i })
                            </li>

                        }

                        else
                        {

                            <li class="ml-3">
                                @Html.ActionLink(i.ToString(), "Index", new { SortOrder = ViewBag.SortOrder == null ? "Asc" : ViewBag.SortOrder, SortBy = ViewBag.SortBy == null ? "Name" : ViewBag.SortBy, PageNumber = i })
                            </li>

                        }


                    }



                    <div class="ml-4">

                        @if (ViewBag.PageNumber == totalPages)
                        {

                            <li>
                                @Html.ActionLink("Next", "Index", new { SortOrder = ViewBag.SortOrder == null ? "Asc" : ViewBag.SortOrder, SortBy = ViewBag.SortBy == null ? "Name" : ViewBag.SortBy, PageNumber = ViewBag.PageNumber })
                            </li>
                        }

                        else
                        {

                            <li>
                                @Html.ActionLink("Next", "Index", new { SortOrder = ViewBag.SortOrder == null ? "Asc" : ViewBag.SortOrder, SortBy = ViewBag.SortBy == null ? "Name" : ViewBag.SortBy, PageNumber = ViewBag.PageNumber + 1 })
                            </li>

                        }
                    </div>

                    </ul>

                }

            </div>

        </div>

        </div>

    }
    else
    {
        <p>No such Attendance record created yet</p>
    }

InAndOut/InAndOut/Views/Attendance/Update.cshtml
@model InAndOut.Models.Attendance

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        @*<div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Update Attendance</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-3">
                        <label asp-for="AttendanceDate"></label>
                    </div>
                    <div class="col-3">
                        <label asp-for="ArrivalTime"></label>
                    </div>
                    <div class="col-3">
                        <label asp-for="DepartureTime"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-3">
                        <input asp-for="AttendanceDate" class="form-control" />
                        <span asp-validation-for="AttendanceDate" class="text-danger"></span>
                    </div>
                    <div class="col-3">
                        <input asp-for="ArrivalTime" class="form-control" />
                        <span asp-validation-for="ArrivalTime" class="text-danger"></span>
                    </div>
                    <div class="col-3">
                        <input asp-for="DepartureTime" class="form-control" />
                        <span asp-validation-for="DepartureTime" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" 
                                   class="btn btn-outline-info w-75"
                                   onclick="return confirm('Are you sure you want to Update the record')"
                                   value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-outline-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}