InAndOut/InAndOut/Controllers/ExpenseTypeController.cs
using InAndOut.Data;
using InAndOut.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Controllers
{
    public class ExpenseTypeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ExpenseTypeController(ApplicationDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            IEnumerable<ExpenseType> objList = _db.ExpenseTypes;
            return View(objList);
            
        }

        // GET-Create
        public IActionResult Create()
        {
            return View();
        }

        // POST-Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ExpenseType obj)
        {
            if (ModelState.IsValid)
            {
                _db.ExpenseTypes.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
           
        }


        // GET Delete
        public IActionResult Delete(int? id)
        {
           
            if (id == null || id==0)
            {
                return NotFound();
            }
            var obj = _db.ExpenseTypes.Find(id);
            if(obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        // POST Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.ExpenseTypes.Find(id);
            if(obj == null)
            {
                return NotFound();
            }
           
            _db.ExpenseTypes.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

        // GET Update
        public IActionResult Update(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.ExpenseTypes.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        // POST UPDATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ExpenseType obj)
        {
            if (ModelState.IsValid)
            {
                _db.ExpenseTypes.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);

        }
    }
}

InAndOut/InAndOut/Views/ExpenseType/Create.cshtml
@model InAndOut.Models.ExpenseType

<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Expense Type</h2> 
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Name"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                   
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-outline-info w-75" value="create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-outline-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{ 
    @{ <partial name="_ValidationScriptsPartial" />}
}

InAndOut/InAndOut/Views/ExpenseType/Delete.cshtml
@model InAndOut.Models.ExpenseType

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Delete Expense Type</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Name"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" 
                                   onclick="return confirm('Are you sure you want to Delete the record')"
                                   class="btn btn-outline-danger w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-outline-success w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
}
    }

InAndOut/InAndOut/Views/ExpenseType/Index.cshtml
@model IEnumerable<InAndOut.Models.ExpenseType>

@{
    ViewData["Title"] = "Expense Type";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Expense Type List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="ExpenseType" asp-action="Create" class="btn btn-outline-primary">Create new Expense Type</a>
        </div>
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-sm">
            <thead>
                <tr>
                    <th>
                        Expense
                    </th>
                    <th style="text-align:center">
                        Changes
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="35%">@obj.Name</td>
                        <td style="text-align:center" width="30%">
                            <div class="w-100 btn-group" role="group">
                                <a asp-controller="ExpenseType" asp-action="Update" asp-route-Id="@obj.Id" class="btn btn-outline-primary mx-1">Update</a>
                                <a asp-controller="ExpenseType" asp-action="Delete" asp-route-Id="@obj.Id" class="btn btn-outline-danger mx-1">Delete</a>

                                

                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No items created yet</p>
    }

</div>

InAndOut/InAndOut/Views/ExpenseType/Update.cshtml
@model InAndOut.Models.ExpenseType

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">

        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Update Expense Type</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Name"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" 
                                   onclick="return confirm('Are you sure you want to Update the record')"
                                   class="btn btn-outline-info w-75" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-outline-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
}
}